export const adminToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwidXNlcklkIjozMTgsInJvbGUiOjEsImlhdCI6MTU4NjQyNTU4M30.OdE_EfHY_ZdAcTE8nDgvKY4llhs4OFRxOfqFQDOP9wU';
export const regularToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InJlZ3VsYXJVc2VyIiwidXNlcklkIjo0NDIsInJvbGUiOjIsImlhdCI6MTU4NjQyOTQ3N30.SjhrVUwhg9dVy9xE_pqWBBWr157BkVfheTXCAV9mDS8';
